import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import LinkButton from '../components/LinkButton';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome<a href='https://nextjs.org'> Friend</a>
        </h1>

        <div className={styles.grid}>
          <LinkButton link='/about' desc='About' />

          <LinkButton link='/contact' desc='Contact' />

          <LinkButton link='/blog' desc='Blog' />

          <LinkButton link='/projects' desc='Projects' />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'>
          Powered by
          <span className={styles.logo}>
            <Image
              src='/vercel.svg'
              alt='Nkangi Jafari logo'
              width={72}
              height={16}
            />
          </span>
        </a>
      </footer>
    </div>
  );
}
